# server port
# web.xml
# session(1800 seconds = 30 minutes)
server:
  port: 9090
  servlet: 
    encoding: 
      charset: UTF-8
      enabled: true
      force: true
    session: 
      timeout: 1800




# database connection
# mail
spring:

#  main:
#    web-application-type: none  # not use embeded tomcat

  datasource:
    hikari: 
      driver-class-name: com.mysql.cj.jdbc.Driver
      # driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:mysql://localhost:3306/bulmeong?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#      jdbc-url: jdbc:mysql://203.245.44.15:3306/bulmeong?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      # jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/bulmeong?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#      username: bulmeong
      username: root
 #     password: asdf1235!
      password: 1111
  mail: 
    host: smtp.gmail.com
    port: 587
    username: moon97102002@gmail.com
    password: whlhxpaugzvysjvl
    properties:
      mail: 
        smtp: 
          auth: true
          starttls: 
            enable: true
#  servlet:
#    multipart:
#     enabled: true
#      max-file-size: 10MB
#     max-request-size: 10MB


# mybatis
mybatis:
  config-location: mybatis/config/mybatis-config.xml
  mapper-locations: mybatis/mapper/*.xml
  