DROP TABLE "PAY";
DROP TABLE "RESERVE";
DROP TABLE "CAMP_TENT";
DROP TABLE "CAMP_CART";
DROP TABLE "REVIEW_CMT";
DROP TABLE "REVIEW_BRD";
DROP TABLE "CAMP";
DROP TABLE "FAQ";
DROP TABLE "NOTICE";
DROP TABLE "QNA";
DROP TABLE "USED_CART";
DROP TABLE "USED_CMT";
DROP TABLE "USED_BRD";
DROP TABLE "FREE_CMT";
DROP TABLE "FREE_LIKE";
DROP TABLE "FREE_BRD";
DROP TABLE "USERS_ACCESS";
DROP TABLE "USERS_RETIRE";
DROP TABLE "USERS_SLEEP";
DROP TABLE "USERS";

CREATE TABLE "USERS" (
   "USERS_NO"   NUMBER      NOT NULL,
   "ID"   VARCHAR2(50 BYTE)      NOT NULL UNIQUE,
   "NICKNAME"   VARCHAR2(50 BYTE)      NOT NULL UNIQUE,
   "PW"   VARCHAR2(64 BYTE)      NOT NULL,
   "NAME"   VARCHAR2(50 BYTE)      NOT NULL,
   "MOBILE"   VARCHAR2(11 BYTE)      NOT NULL,
   "GENDER"   VARCHAR2(2 BYTE)      NOT NULL,
   "BIRTH_YEAR"   VARCHAR2(4 BYTE)      NULL,
   "BIRTH_DAY"   VARCHAR2(4 BYTE)      NULL,
   "POSTCODE"   VARCHAR2(5 BYTE)      NULL,
   "ROAD_ADDRESS"   VARCHAR2(100 BYTE)      NULL,
   "JIBUN_ADDRESS"   VARCHAR2(100 BYTE)      NULL,
   "DETAIL_ADDRESS"   VARCHAR2(100 BYTE)      NULL,
   "EXTRA_ADDRESS"   VARCHAR2(100 BYTE)      NULL,
   "JOIN_DATE"   VARCHAR2(20 BYTE)      NOT NULL,
   "AGREE_CODE"   NUMBER      NOT NULL,
   "SNS_TYPE"   VARCHAR2(10 BYTE)      NULL,
   "SESSION_ID"   VARCHAR2(46 BYTE)      NULL,
   "SESSION_LIMIT_DATE"   VARCHAR2(20 BYTE)      NULL,
   "POINT"   NUMBER      NOT NULL,
   "EMAIL"   VARCHAR2(100 BYTE)      NOT NULL UNIQUE,
   "AGE"   NUMBER      NULL,
   "PROFILE_IMAGE"   VARCHAR2(255 BYTE)      NULL
);

CREATE TABLE "USERS_SLEEP" (
   "USERS_NO"   NUMBER      NOT NULL,
   "ID"   VARCHAR2(50 BYTE)      NOT NULL,
   "NICKNAME"   VARCHAR2(50 BYTE)      NOT NULL,
   "PW"   VARCHAR2(64 BYTE)      NOT NULL,
   "NAME"   VARCHAR2(50 BYTE)      NOT NULL,
   "MOBILE"   VARCHAR2(11 BYTE)      NOT NULL,
   "GENDER"   VARCHAR2(2 BYTE)      NOT NULL,
   "BIRTH_YEAR"   VARCHAR2(4 BYTE)      NULL,
   "BIRTH_DAY"   VARCHAR2(4 BYTE)      NULL,
   "POSTCODE"   VARCHAR2(5 BYTE)      NULL,
   "ROAD_ADDRESS"   VARCHAR2(100 BYTE)      NULL,
   "JIBUN_ADDRESS"   VARCHAR2(100 BYTE)      NULL,
   "DETAIL_ADDRESS"   VARCHAR2(100 BYTE)      NULL,
   "EXTRA_ADDRESS"   VARCHAR2(100 BYTE)      NULL,
   "JOIN_DATE"   VARCHAR2(20 BYTE)      NOT NULL,
   "AGREE_CODE"   NUMBER      NOT NULL,
   "SNS_TYPE"   VARCHAR2(10 BYTE)      NULL,
   "SESSION_ID"   VARCHAR2(46 BYTE)      NULL,
   "SESSION_LIMIT_DATE"   VARCHAR2(20 BYTE)      NULL,
   "POINT"   NUMBER      NOT NULL,
   "EMAIL"   VARCHAR2(50 BYTE)      NOT NULL,
   "SLEEP_DATE"   VARCHAR2(20 BYTE)      NULL,
   "AGE"   NUMBER      NULL,
   "PROFILE_IMAGE"   VARCHAR2(255 BYTE)      NULL,
   "LAST_LOGIN_DATE"   VARCHAR2(20 BYTE)      NULL
);

CREATE TABLE "USERS_RETIRE" (
   "RETIRE_NO"   NUMBER      NOT NULL,
   "ID"   VARCHAR2(46 BYTE)      NOT NULL,
   "RETIRE_DATE"   VARCHAR2(20 BYTE)      NULL,
   "JOIN_DATE"   VARCHAR2(20 BYTE)      NULL
);

CREATE TABLE "USERS_ACCESS" (
   "ID"   VARCHAR2(50 BYTE)      NOT NULL,
   "LAST_LOGIN_DATE"   VARCHAR2(20 BYTE)      NOT NULL
);

CREATE TABLE "FREE_BRD" (
   "FREE_NO"   NUMBER      NOT NULL,
   "NICKNAME"   VARCHAR2(50 BYTE)      NOT NULL,
   "FREE_TITLE"   VARCHAR2(40 BYTE)      NOT NULL,
   "FREE_CONTENT"   VARCHAR2(500 BYTE)      NULL,
   "FREE_CREATE_DATE"   VARCHAR2(20 BYTE)      NOT NULL,
   "FREE_MODIFIY_DATE"   VARCHAR2(20 BYTE)      NOT NULL,
   "FREE_IP"   VARCHAR2(30 BYTE)      NOT NULL,
   "FREE_HIT"   NUMBER      NOT NULL
);

CREATE TABLE "FREE_LIKE" (
   "FREE_NO"   NUMBER      NOT NULL,
   "NICKNAME"   VARCHAR2(50 BYTE)      NOT NULL
);

CREATE TABLE "FREE_CMT" (
   "FREE_CMT_NO"   NUMBER      NOT NULL,
   "FREE_NO"   NUMBER      NOT NULL,
   "NICKNAME"   VARCHAR2(50 BYTE)      NOT NULL,
   "FREE_CMT_CONTENT"   VARCHAR2(500 BYTE)      NOT NULL,
   "FREE_CMT_CREATE_DATE"   VARCHAR2(20 BYTE)      NOT NULL,
   "FREE_CMT_MODIFY_DATE"   VARCHAR2(20 BYTE)      NULL,
   "FREE_CMT_IP"   VARCHAR2(30 BYTE)      NOT NULL,
   "FREE_CMT_STATE"   NUMBER(1,0)      NOT NULL,
   "FREE_CMT_DEPTH"   NUMBER(2,0)      NOT NULL,
   "FREE_GROUP_NO"   NUMBER      NOT NULL,
   "FREE_GROUP_ORDER"   NUMBER      NOT NULL
);

CREATE TABLE "USED_BRD" (
   "USED_NO"   NUMBER      NOT NULL,
   "NICKNAME"   VARCHAR2(50 BYTE)      NOT NULL,
   "USED_TITLE"   VARCHAR2(40 BYTE)      NOT NULL,
   "USED_CONTENT"   VARCHAR2(500 BYTE)      NULL,
   "USED_CREATE_DATE"   VARCHAR2(20 BYTE)      NOT NULL,
   "USED_MODIFIY_DATE"   VARCHAR2(20 BYTE)      NOT NULL,
   "USED_IP"   VARCHAR2(30 BYTE)      NOT NULL,
   "USED_HIT"   NUMBER      NOT NULL
);

CREATE TABLE "USED_CMT" (
   "USED_CMT_NO"   NUMBER      NOT NULL,
   "USED_NO"   NUMBER      NOT NULL,
   "NICKNAME"   VARCHAR2(50 BYTE)      NOT NULL,
   "USED_CMT_CONTENT"   VARCHAR2(500 BYTE)      NOT NULL,
   "USED_CMT_CREATE_DATE"   VARCHAR2(20 BYTE)      NOT NULL,
   "USED_CMT_MODIFY_DATE"   VARCHAR2(20 BYTE)      NULL,
   "USED_CMT_IP"   VARCHAR2(30 BYTE)      NOT NULL,
   "USED_CMT_STATE"   NUMBER(1,0)      NOT NULL,
   "USED_CMT_DEPTH"   NUMBER(2,0)      NOT NULL,
   "USED_GROUP_NO"   NUMBER      NOT NULL,
   "USED_GROUP_ORDER"   NUMBER      NOT NULL
);

CREATE TABLE "USED_CART" (
   "USED_NO"   NUMBER      NOT NULL,
   "NICKNAME"   VARCHAR2(50 BYTE)      NOT NULL
);

CREATE TABLE "QNA" (
   "QNA_NO"   NUMBER      NOT NULL,
   "ID"   VARCHAR2(50 BYTE)      NOT NULL,
   "QNA_TITLE"   VARCHAR2(40 BYTE)      NOT NULL,
   "QNA_CONTENT"   VARCHAR2(3000 BYTE)      NULL,
   "QNA_CREATE_DATE"   VARCHAR2(20 BYTE)      NULL,
   "QNA_MODIFY_DATE"   VARCHAR2(20 BYTE)      NULL,
   "QNA_STATE"   NUMBER(1,0)      NOT NULL,
   "QNA_IP"   VARCHAR2(30 BYTE)      NOT NULL,
   "QNA_GROUP_NO"   NUMBER      NOT NULL,
   "DEPTH"   NUMBER(2)      NOT NULL
);

CREATE TABLE "NOTICE" (
   "NOTICE_NO"   NUMBER      NOT NULL,
   "NOTICE_TITLE"   VARCHAR2(40 BYTE)      NOT NULL,
   "NOTICE_CONTENT"   VARCHAR2(3000 BYTE)      NOT NULL,
   "NOTICE_HIT"   NUMBER      NOT NULL,
   "NOTICE_CREATE_DATE"   VARCHAR2(20 BYTE)      NULL,
   "NOTICE_MODIFY_DATE"   VARCHAR2(20 BYTE)      NULL,
   "ID"   VARCHAR2(50 BYTE)      NOT NULL
);

CREATE TABLE "FAQ" (
   "FAQ_NO"   NUMBER      NOT NULL,
   "FAQ_TITLE"   VARCHAR2(50 BYTE)      NOT NULL,
   "FAQ_CONTENT"   VARCHAR2(3000 BYTE)      NOT NULL,
   "FAQ_CREATE_DATE"   VARCHAR2(20 BYTE)      NULL
);

CREATE TABLE "CAMP" (
   "CAMP_NO"   NUMBER      NOT NULL,
   "REVIEW_NO"   NUMBER      NOT NULL,
   "facltNm"   VARCHAR2(64 BYTE)      NOT NULL,
   "lineIntro"   VARCHAR2(1000 BYTE)      NOT NULL,
   "featureNm"   VARCHAR2(64 BYTE)      NULL,
   "sbrsCl"   VARCHAR2(64 BYTE)      NULL,
   "firstImageUrl"   VARCHAR2(300 BYTE)      NULL,
   "themaEnvrnCl"   VARCHAR2(64 BYTE)      NULL,
   "eqpmnLendCl"   VARCHAR2(64 BYTE)      NULL,
   "tourEraCl"   VARCHAR2(64 BYTE)      NULL,
   "induty"   VARCHAR2(64 BYTE)      NULL,
   "allar"   NUMBER      NULL,
   "operPdCl"   VARCHAR2(64 BYTE)      NULL,
   "hvofBgnde"   VARCHAR2(64 BYTE)      NULL,
   "hvofEnddle"   VARCHAR2(64 BYTE)      NULL,
   "prmisnDe"   VARCHAR2(64 BYTE)      NULL,
   "operDeCl"   VARCHAR2(64 BYTE)      NULL,
   "toiletCo"   NUMBER      NULL,
   "extshrCo"   NUMBER      NULL,
   "brazierCl"   NUMBER      NULL,
   "glampInnerFclty"   VARCHAR2(64 BYTE)      NULL,
   "caravInnerFclty"   VARCHAR2(64 BYTE)      NULL,
   "lctCl"   VARCHAR2(64 BYTE)      NULL,
   "addr1"   VARCHAR2(64 BYTE)      NULL,
   "doNm"   VARCHAR2(64 BYTE)      NULL,
   "sigunguNm"   VARCHAR2(64 BYTE)      NULL,
   "addr2"   VARCHAR2(64 BYTE)      NULL,
   "zipcode"   VARCHAR2(64 BYTE)      NULL,
   "mapX"   VARCHAR2(64 BYTE)      NULL,
   "mapY"   VARCHAR2(64 BYTE)      NULL,
   "homepage"   VARCHAR2(300 BYTE)      NULL,
   "tel"   VARCHAR2(64 BYTE)      NULL,
   "createdtime"   VARCHAR2(64 BYTE)      NULL,
   "modifiedtime"   VARCHAR2(64 BYTE)      NULL
);

CREATE TABLE "REVIEW_BRD" (
   "REVIEW_NO"   NUMBER      NOT NULL,
   "CAMP_NO"   NUMBER      NOT NULL,
   "ID"   VARCHAR2(50 BYTE)      NOT NULL,
   "REVIEW_TITLE"   VARCHAR2(40 BYTE)      NOT NULL,
   "REVIEW_CONTENT"   VARCHAR2(500 BYTE)      NULL,
   "REVIEW_CREATE_DATE"   VARCHAR2(20 BYTE)      NOT NULL,
   "REVIEW_MODIFIY_DATE"   VARCHAR2(20 BYTE)      NOT NULL,
   "REVIEW_IP"   VARCHAR2(30 BYTE)      NOT NULL,
   "REVIEW_HIT"   NUMBER      NOT NULL,
   "REVIEW_STAR"   NUMBER      NOT NULL
);

CREATE TABLE "REVIEW_CMT" (
   "REVIEW_CMT_NO"   NUMBER      NOT NULL,
   "REVIEW_NO"   NUMBER      NOT NULL,
   "ID"   VARCHAR2(50 BYTE)      NOT NULL,
   "REVIEW_CMT_CONTENT"   VARCHAR2(500 BYTE)      NOT NULL,
   "REVIEW_CMT_CREATE_DATE"   VARCHAR2(20 BYTE)      NOT NULL,
   "REVIEW_CMT_MODIFY_DATE"   VARCHAR2(20 BYTE)      NULL,
   "REVIEW_CMT_IP"   VARCHAR2(30 BYTE)      NOT NULL,
   "REVIEW_CMT_STATE"   NUMBER(1,0)      NOT NULL,
   "REVIEW_CMT_DEPTH"   NUMBER(2,0)      NOT NULL,
   "REVIEW_GROUP_NO"   NUMBER      NOT NULL,
   "REVIEW_GROUP_ORDER"   NUMBER      NOT NULL
);

CREATE TABLE "CAMP_CART" (
   "CAMP_CART_NO"   NUMBER      NOT NULL,
   "CAMP_NO"   NUMBER      NOT NULL,
   "ID"   VARCHAR2(50 BYTE)      NOT NULL
);

CREATE TABLE "CAMP_TENT" (
   "TENT_NO"   NUMBER      NOT NULL,
   "CAMP_NO"   NUMBER      NOT NULL,
   "TENT_NAME"   VARCHAR2(64 BYTE)      NOT NULL,
   "TENT_MAX_COUNT"   NUMBER      NOT NULL,
   "TENT_COUNT"   NUMBER      NOT NULL,
   "TENT_PERIOD"   VARCHAR2(64 BYTE)      NOT NULL,
   "TENT_SUM"   NUMBER      NOT NULL
);

CREATE TABLE "RESERVE" (
   "RESERVE_NO"   NUMBER      NOT NULL,
   "CAMP_NO"   NUMBER      NOT NULL,
   "TENT_NO"   NUMBER      NOT NULL,
   "ID"   VARCHAR2(50 BYTE)      NOT NULL,
   "RESERVE_SUM"   NUMBER      NOT NULL,
   "RESERVE_DATE"   VARCHAR2(64 BYTE)      NOT NULL,
   "RESERVE_CANCEL"   VARCHAR2(64 BYTE)      NULL,
   "RESERVE_STATE"   NUMBER      NOT NULL
);

CREATE TABLE "PAY" (
   "PAY_NO"   NUMBER      NOT NULL,
   "RESERVE_NO"   NUMBER      NOT NULL,
   "PAY_NAME"   VARCHAR2(50 BYTE)      NOT NULL,
   "PAY_DATE"   VARCHAR2(64 BYTE)      NOT NULL
);

-- PK
ALTER TABLE "USERS" ADD CONSTRAINT "PK_USERS" PRIMARY KEY("USERS_NO");
ALTER TABLE "USERS_SLEEP" ADD CONSTRAINT "PK_USERS_SLEEP" PRIMARY KEY("USERS_NO");
ALTER TABLE "FREE_BRD" ADD CONSTRAINT "PK_FREE_BRD" PRIMARY KEY("FREE_NO");
ALTER TABLE "FREE_CMT" ADD CONSTRAINT "PK_FREE_CMT" PRIMARY KEY("FREE_CMT_NO");
ALTER TABLE "USED_BRD" ADD CONSTRAINT "PK_USED_BRD" PRIMARY KEY("USED_NO");
ALTER TABLE "USED_CMT" ADD CONSTRAINT "PK_USED_CMT" PRIMARY KEY("USED_CMT_NO");
ALTER TABLE "CAMP" ADD CONSTRAINT "PK_CAMP" PRIMARY KEY("CAMP_NO");
ALTER TABLE "USERS_RETIRE" ADD CONSTRAINT "PK_USERS_RETIRE" PRIMARY KEY("RETIRE_NO");
ALTER TABLE "CAMP_CART" ADD CONSTRAINT "PK_CAMP_CART" PRIMARY KEY("CAMP_CART_NO");
ALTER TABLE "NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY("NOTICE_NO");
ALTER TABLE "QNA" ADD CONSTRAINT "PK_QNA" PRIMARY KEY("QNA_NO");
ALTER TABLE "FAQ" ADD CONSTRAINT "PK_FAQ" PRIMARY KEY("FAQ_NO");
ALTER TABLE "RESERVE" ADD CONSTRAINT "PK_RESERVE" PRIMARY KEY("RESERVE_NO");
ALTER TABLE "REVIEW_CMT" ADD CONSTRAINT "PK_REVIEW_CMT" PRIMARY KEY("REVIEW_CMT_NO");
ALTER TABLE "REVIEW_BRD" ADD CONSTRAINT "PK_REVIEW_BRD" PRIMARY KEY("REVIEW_NO");
ALTER TABLE "PAY" ADD CONSTRAINT "PK_PAY" PRIMARY KEY("PAY_NO","RESERVE_NO");
ALTER TABLE "CAMP_TENT" ADD CONSTRAINT "PK_CAMP_TENT" PRIMARY KEY("TENT_NO");

-- FK
ALTER TABLE "USERS_ACCESS" ADD CONSTRAINT "FK_ACCESS_USERS" FOREIGN KEY("ID") REFERENCES "USERS" ("ID");
ALTER TABLE "FREE_BRD" ADD CONSTRAINT "FK_FREE_USERS" FOREIGN KEY("NICKNAME") REFERENCES "USERS" ("NICKNAME");
ALTER TABLE "FREE_CMT" ADD CONSTRAINT "FK_FREECMT_FREEBRD" FOREIGN KEY("FREE_NO") REFERENCES "FREE_BRD" ("FREE_NO");
ALTER TABLE "FREE_CMT" ADD CONSTRAINT "FK_FREECMT_USERS" FOREIGN KEY("NICKNAME") REFERENCES "USERS" ("NICKNAME");
ALTER TABLE "FREE_LIKE" ADD CONSTRAINT "FK_FREELIKE_FREEBRD" FOREIGN KEY("FREE_NO") REFERENCES "FREE_BRD" ("FREE_NO");
ALTER TABLE "FREE_LIKE" ADD CONSTRAINT "FK_FREELIKE_USERS" FOREIGN KEY("NICKNAME") REFERENCES "USERS" ("NICKNAME");
ALTER TABLE "USED_BRD" ADD CONSTRAINT "FK_USEDBRD_USERS" FOREIGN KEY("NICKNAME") REFERENCES "USERS" ("NICKNAME");
ALTER TABLE "USED_CMT" ADD CONSTRAINT "FK_USEDCMT_USEDBRD" FOREIGN KEY("USED_NO") REFERENCES "USED_BRD" ("USED_NO");
ALTER TABLE "USED_CMT" ADD CONSTRAINT "FK_USEDCMT_USERS" FOREIGN KEY("NICKNAME") REFERENCES "USERS" ("NICKNAME");
ALTER TABLE "USED_CART" ADD CONSTRAINT "FK_USEDCART_USEDBRD" FOREIGN KEY("USED_NO") REFERENCES "USED_BRD" ("USED_NO");
ALTER TABLE "USED_CART" ADD CONSTRAINT "FK_USEDCART_USERS" FOREIGN KEY("NICKNAME") REFERENCES "USERS" ("NICKNAME");
ALTER TABLE "QNA" ADD CONSTRAINT "FK_QNA_USERS" FOREIGN KEY("ID") REFERENCES "USERS" ("ID");
ALTER TABLE "NOTICE" ADD CONSTRAINT "FK_NOTICE_USERS" FOREIGN KEY("ID") REFERENCES "USERS" ("ID");
ALTER TABLE "REVIEW_BRD" ADD CONSTRAINT "FK_REVIEWBRD_USERS" FOREIGN KEY("ID") REFERENCES "USERS" ("ID");
ALTER TABLE "REVIEW_BRD" ADD CONSTRAINT "FK_REVIEWBRD_CAMP" FOREIGN KEY("CAMP_NO") REFERENCES "CAMP" ("CAMP_NO");
ALTER TABLE "REVIEW_CMT" ADD CONSTRAINT "FK_REVIEWCMT_REVIEWBRD" FOREIGN KEY("REVIEW_NO") REFERENCES "REVIEW_BRD" ("REVIEW_NO");
ALTER TABLE "REVIEW_CMT" ADD CONSTRAINT "FK_REVIEWCMT_USERS" FOREIGN KEY("ID") REFERENCES "USERS" ("ID");
ALTER TABLE "CAMP_CART" ADD CONSTRAINT "FK_CAMPCART_USERS" FOREIGN KEY("ID") REFERENCES "USERS" ("ID");
ALTER TABLE "CAMP_CART" ADD CONSTRAINT "FK_CAMPCART_CAMP" FOREIGN KEY("CAMP_NO") REFERENCES "CAMP" ("CAMP_NO");
ALTER TABLE "RESERVE" ADD CONSTRAINT "FK_RESERVE_USERS" FOREIGN KEY("ID") REFERENCES "USERS" ("ID");
ALTER TABLE "RESERVE" ADD CONSTRAINT "FK_RESERVE_CAMP" FOREIGN KEY("CAMP_NO") REFERENCES "CAMP" ("CAMP_NO");
ALTER TABLE "RESERVE" ADD CONSTRAINT "FK_RESERVE_CAMPTENT" FOREIGN KEY("TENT_NO") REFERENCES "CAMP_TENT" ("TENT_NO");
ALTER TABLE "CAMP_TENT" ADD CONSTRAINT "FK_CAMPTENT_CAMP" FOREIGN KEY("CAMP_NO") REFERENCES "CAMP" ("CAMP_NO");
ALTER TABLE "PAY" ADD CONSTRAINT "FK_PAY_RESERVE" FOREIGN KEY("RESERVE_NO") REFERENCES "RESERVE" ("RESERVE_NO");

-- SEQUENCE
DROP SEQUENCE USERS_NO_SEQ;
DROP SEQUENCE SLEEP_NO_SEQ;
DROP SEQUENCE RETIRE_NO_SEQ;
DROP SEQUENCE FREE_CMT_NO_SEQ;
DROP SEQUENCE FREE_NO_SEQ;
DROP SEQUENCE USED_CMT_NO_SEQ;
DROP SEQUENCE USED_BRD_NO_SEQ;
DROP SEQUENCE USED_CART_NO_SEQ;
DROP SEQUENCE REVIEW_CMT_NO_SEQ;
DROP SEQUENCE REVIEW_NO_SEQ;
DROP SEQUENCE CAMP_CART_NO_SEQ;
DROP SEQUENCE CAMP_NO_SEQ;
DROP SEQUENCE TENT_NO_SEQ;
DROP SEQUENCE PAY_NO_SEQ;
DROP SEQUENCE RESERVE_NO_SEQ;
DROP SEQUENCE NOTICE_NO_SEQ;
DROP SEQUENCE FAQ_NO_SEQ;
DROP SEQUENCE QNA_NO_SEQ;

CREATE SEQUENCE USERS_NO_SEQ NOCACHE;
CREATE SEQUENCE SLEEP_NO_SEQ NOCACHE;
CREATE SEQUENCE RETIRE_NO_SEQ NOCACHE;
CREATE SEQUENCE FREE_CMT_NO_SEQ NOCACHE;
CREATE SEQUENCE FREE_NO_SEQ NOCACHE;
CREATE SEQUENCE USED_CMT_NO_SEQ NOCACHE;
CREATE SEQUENCE USED_BRD_NO_SEQ NOCACHE;
CREATE SEQUENCE USED_CART_NO_SEQ NOCACHE;
CREATE SEQUENCE REVIEW_CMT_NO_SEQ NOCACHE;
CREATE SEQUENCE REVIEW_NO_SEQ NOCACHE;
CREATE SEQUENCE CAMP_CART_NO_SEQ NOCACHE;
CREATE SEQUENCE CAMP_NO_SEQ NOCACHE;
CREATE SEQUENCE TENT_NO_SEQ NOCACHE;
CREATE SEQUENCE PAY_NO_SEQ NOCACHE;
CREATE SEQUENCE RESERVE_NO_SEQ NOCACHE;
CREATE SEQUENCE NOTICE_NO_SEQ NOCACHE;
CREATE SEQUENCE FAQ_NO_SEQ NOCACHE;
CREATE SEQUENCE QNA_NO_SEQ NOCACHE;

-- 관리자
INSERT INTO USERS
    (USERS_NO, ID, NICKNAME, PW, NAME, MOBILE, GENDER, BIRTH_YEAR, BIRTH_DAY, POSTCODE, ROAD_ADDRESS, JIBUN_ADDRESS, DETAIL_ADDRESS, EXTRA_ADDRESS, JOIN_DATE, AGREE_CODE, SNS_TYPE, SESSION_ID, SESSION_LIMIT_DATE, POINT, EMAIL, AGE, PROFILE_IMAGE)
VALUES
    (USERS_NO_SEQ.NEXTVAL, 'ADMIN', '관리자', '9BDB4EA68F6F65EC4D5F 3781636525CB2943BFD1E599D34B186BA77F1D8CE9F', '관리자', '01055555555', 'M', '2022', '1208', '55555', '도로명주소', '지번주소', '상세주소', '참고주소', TO_CHAR(SYSDATE, 'YY/MM/DD'), 1, NULL, 'ADMIN', '99/01/03', 0, 'ADMIN@NAVER.COM', 60, NULL);

-- 유저
INSERT INTO USERS VALUES(USERS_NO_SEQ.NEXTVAL, 'user01', 'u01', '9BDB4EA68F6F65EC4D5F 3781636525CB2943BFD1E599D34B186BA77F1D8CE9F', 'user01', '01012341234', 'M', '1990', '0705', '11111', 'ROAD1', 'JIBUN1', 'DETAIL1', 'EXTRA1', TO_CHAR(SYSDATE, 'YY/MM/DD'), 0, NULL, NULL, NULL, 
0, 'user01@naver.com', 33, 'download01.img');

INSERT INTO USERS VALUES(USERS_NO_SEQ.NEXTVAL, 'user02', 'u02', '9BDB4EA68F6F65EC4D5F 3781636525CB2943BFD1E599D34B186BA77F1D8CE9F', 'user02', '01012345678', 'M', '1994', '0629', '22222', 'ROAD2', 'JIBUN2', 'DETAIL2', 'EXTRA2', TO_CHAR(SYSDATE, 'YY/MM/DD'), 2, NULL, NULL, NULL, 
0, 'user02@naver.com', 29, 'download02.img');

INSERT INTO USERS VALUES(USERS_NO_SEQ.NEXTVAL, 'user03', 'u03', '9BDB4EA68F6F65EC4D5F 3781636525CB2943BFD1E599D34B186BA77F1D8CE9F', 'user03', '01012123434', 'M', '1998', '0428', '33333', 'ROAD3', 'JIBUN3', 'DETAIL3', 'EXTRA3', TO_CHAR(SYSDATE, 'YY/MM/DD'), 3, NULL, NULL, NULL, 
0, 'user03@naver.com', 25, 'download03.img');

INSERT INTO USERS_ACCESS VALUES('user03', '20/01/01');  -- 휴면

COMMIT;
    